ALTER TABLE `order`
DROP COLUMN customer_id;

ALTER TABLE `order`
ADD user_id NUMBER NOT NULL;

ALTER TABLE `order`
ADD CONSTRAINT CONSTRAINT FK__ORDER__USER FOREIGN KEY (user_id) REFERENCES `user`(id);